// Concatenates the ExtendScript sources (src/illustrator/jsx/NN-*.jsx) into
// the single host.jsx loaded by the CEP manifest. Non-ASCII characters are
// escaped as \uXXXX so the file is safe regardless of ExtendScript's encoding
// detection (it has no BOM).
import { readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const JSX_DIR = join(ROOT, 'src', 'illustrator', 'jsx');

export function jsxFiles() {
  return readdirSync(JSX_DIR)
    .filter((f) => /^\d\d-.*\.jsx$/.test(f))
    .sort();
}

export function escapeNonAscii(src) {
  return src.replace(/[^\x00-\x7f]/g, (c) => '\\u' + c.charCodeAt(0).toString(16).toUpperCase().padStart(4, '0'));
}

export function buildHostSource(version = '0.0.0') {
  const parts = jsxFiles().map((f) => `// ---- ${f} ----\n` + readFileSync(join(JSX_DIR, f), 'utf8'));
  const banner = `/* Artboard Forge host ${version} — generated by scripts/build.mjs. Do not edit; edit src/illustrator/jsx/*.jsx. */\n`;
  return escapeNonAscii(banner + parts.join('\n'));
}
